#!/usr/bin/env bash

cd "$(dirname "$0")"

git add .
git commit -m "Automatic update $(date +"%T %D")"

tracked="$(git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD))"
if [[ -n "$tracked" ]]; then
    git fetch --all -p
    if git rebase $tracked; then
        git push
    else
        git rebase --abort
    fi
fi
