#!/usr/bin/env bash
shopt -s dotglob

orig_root=$(cd "$(dirname "$0")"; pwd)
if [[ !("${orig_root%/*/?}" == "${HOME%/}"/*) ]]; then
    echo 'Dotfiles must be on the same volume as $HOME!'
    echo "HOME:     $HOME"
    echo "Dotfiles: $orig_root"
    exit 1
fi

run_on_configs=false
run_on_dotfiles=false
run_on_firefox=false
run_on_git=false
run_on_moreutils=false
run_on_scripts=false
uninstall=false

function install {
    if [[ "$1" == false ]]; then
        return
    fi
    echo "${verb:-Installing} $2..."
    src="$orig_root/$3"
    dest="$4"

    output=false
    mkdir -p "$dest"
    for item in "${src%/}"/*; do
        if [[ ! -d "$item" ]]; then
            if [[ "$uninstall" == false ]]; then
                ln -fv "$item" "$dest"
                output=true
            else
                target="$dest/$(basename "$item")"
                if  rm "$target" > /dev/null 2>&1; then
                    echo "$target -> removed"
                    output=true
                fi
            fi
        fi
    done
    if [[ "$output" == true ]]; then
        echo ''
    fi
}

function print_help {
    echo 'Usage: install [-acdfmsu] [firefox profile list...]'
    echo 'Description: Installs selected features to your machine'
    echo '    -a    Select all features'
    echo '    -c    Select configs'
    echo '    -d    Select dotfiles'
    echo '    -f    Select firefox features'
    echo '    -m    Select moreutils'
    echo '    -s    Select helper scripts'
    echo '    -u    Uninstall selected features'
    echo ''
    exit 1
}


# Process command line
while getopts 'acdfmsu' opt; do
    case $opt in
        h) print_help ;;

        a) run_on_configs=true
           run_on_dotfiles=true
           run_on_firefox=true
           run_on_moreutils=true
           run_on_scripts=true
           ;;

        c) run_on_configs=true   ;;
        d) run_on_dotfiles=true  ;;
        f) run_on_firefox=true   ;;
        m) run_on_moreutils=true ;;
        s) run_on_scripts=true   ;;

        u) uninstall=true
           verb='Uninstalling'
           ;;
    esac
done
shift $((OPTIND -1))
firefox_profiles=${@:-"./*/"}

if [[ "$run_on_configs"   == false \
   && "$run_on_dotfiles"  == false \
   && "$run_on_firefox"   == false \
   && "$run_on_moreutils" == false \
   && "$run_on_scripts"   == false ]]; then
    print_help
fi

# Install features
install "$run_on_configs"   'configs'   'configs'   "$HOME/.config"
install "$run_on_dotfiles"  'dotfiles'  'dotfiles'  "$HOME"
install "$run_on_moreutils" 'moreutils' 'moreutils' '/usr/local/bin'
install "$run_on_scripts"   'scripts'   'scripts'   "$HOME"

if [[ "$run_on_firefox" == true ]]; then
    case "$(uname -s)" in
        Darwin*) firefox_root="$HOME/Library/Application Support/Firefox/Profiles" ;;
        *)       firefox_root="$HOME/.mozilla/Firefox"                             ;;
    esac

    echo "${verb:-Installing} Firefox tweaks..."
    cd "$firefox_root"
    for profile in $firefox_profiles; do # $firefox_profiles here unquoted for expansion
        if [[ !(-d "$profile") ]]; then
            echo "Profile '$profile' does not exist, ignoring"
            continue
        fi
        profile_dest=$(cd "$profile"; pwd)
        install true "$(basename "$profile_dest")" 'Firefox' "$profile_dest/chrome"
    done
fi


echo 'Done!'
